### ISSUE TITLE
Excuse me, I'm not sure whether the raw parameter here should be true?

### ISSUE THREAD

**Issue by caobingsheng** [xo/tblfmt#34]
https://github.com/xo/tblfmt/blob/9cf97d88b98e9b0d0520bbe9a843913725dec394/fmt.go#L117

**Comment by nineinchnick** [comment]
Why do you think so? The comment for this parameter says:
```
// Raw tracks whether or not the value should be encoded or not.
```
Why would bools need to be encoded? Encoding means quoting the value when printing:
https://github.com/xo/tblfmt/blob/9cf97d88b98e9b0d0520bbe9a843913725dec394/encode.go#L916

**Comment by caobingsheng** [comment]
Yes, I noticed this judgment, but when I use usql, I find that when I use the -J parameter to output json, the bool type field in the database outputs "false", for example ("logic": "false")

**Comment by nineinchnick** [comment]
And what do you expect it to output?

**Comment by nineinchnick** [comment]
What database are you using? Are you sure you're querying a boolean column? Maybe the database driver returns boolean as strings.

**Comment by kenshaw** [comment]
To echo @nineinchnick, this is likely due to the driver you're using. What database are you connecting to, and could you share a sample schema that we could quickly check against? Thanks.

**Comment by caobingsheng** [comment]
[test_bool.zip](https://github.com/xo/tblfmt/files/9078051/test_bool.zip)
usql version: 0.10.0
os version: Windows 10 20H2 19042.1466
The test_bool.zip  file contains the sample schema SQL file

**Comment by kenshaw** [comment]
I just pushed a fix for this. This was an oversight only on the `bool` type within the formatter.
